# Generated by Django 5.1.1 on 2024-10-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_info', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_of_staff', models.TextField(null=True)),
                ('punctuality', models.DateTimeField(auto_now=True)),
                ('closing_remarks', models.TimeField(auto_now=True)),
                ('archieved', models.BooleanField(default=False)),
                ('percentahe_completion', models.IntegerField(default=0)),
            ],
        ),
    ]
