# Generated by Django 5.1.1 on 2024-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=300, null=True),
        ),
    ]
